### ISSUE TITLE
Username/Password for logging in.

### ISSUE THREAD

**Issue by apanimesh061** [lduarte1991/hx-annotations-lti#1]
I am new to this project. I have been successful in making the project run but I cannot understand where to start. I was able to get to the admin's page but after that what? Is there a test username/password that you have to testing 'cause I could not find any in the source code?

Thanks

**Comment by lduarte1991** [comment]
Hi there,

Are you part of HUIT/ATG or IQSS? If so, keep in mind that in a few days we will have documentation and guidance as promised before the scheduled meeting.

If it's for a personal project, please note that this project is currently in development, or to be more precise incomplete and not ready for production. Thus, to answer your question there is nothing to start with yet as it is incomplete/in-development.

**Comment by apanimesh061** [comment]
I am currently working at IQSS. I started this week itself. I'll wait for
te documentation then. Thanks.

On Tue, May 19, 2015 at 5:21 PM, lduarte1991 <notifications@github.com>
wrote:

> Hi there,
>
> Are you part of HUIT/ATG or IQSS? If so, keep in mind that in a few days
> we will have documentation and guidance as promised before the scheduled
> meeting.
>
> If it's for a personal project, please note that this project is currently
> in development, or to be more precise incomplete and not ready for
> production. Thus, to answer your question there is nothing to start with
> yet as it is incomplete/in-development.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lduarte1991/hx-annotations-lti/issues/1#issuecomment-103670232>
> .
>



-- 
Thanks and regards,
Animesh Pandey
Graduate Student
Northeastern University
Boston, MA, USA

**Comment by lduarte1991** [comment]
No worries! I would take a look a the residential branch, though, it might be a bit more helpful for what you would need. In particular the static folder within hx_lti_initializer. Good luck

**Comment by apanimesh061** [comment]
Hi,
Is it possible if you could let me know some URLs that work for this
application?
The only URL that I could I could figure out was the admin's console which
I can't log into.

On Tue, May 19, 2015 at 6:47 PM, lduarte1991 <notifications@github.com>
wrote:

> No worries! I would take a look a the residential branch, though, it might
> be a bit more helpful for what you would need. In particular the static
> folder within hx_lti_initializer. Good luck
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lduarte1991/hx-annotations-lti/issues/1#issuecomment-103689543>
> .
>



-- 
Thanks and regards,
Animesh Pandey
Graduate Student
Northeastern University
Boston, MA, USA

**Comment by lduarte1991** [comment]
Unfortunately, I don't have much time to help debug (sorry!), but here's some things that might help you: 

I would recommend you read up on the [LTI Framework](http://www.imsglobal.org/LTI/v1p1/ltiIMGv1p1.html) and how it works. You can't just go to the URL of the tool, it's an LTI tool, so you need something like a launcher on edX or Canvas or your own personal server, and requires access via the [initializer](https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer). You need to point it to the consumer URL of the server you're running it from [here](https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer/__init__.py). And then validate it using the functions [here](https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer/views.py). 

Any other URLs can be found in the patterns within the urls.py files throughout the different apps.

Make sure you have a handle on LTI and Django, otherwise the set up won't make sense. If all you need is the Annotator component of it, skip the set up above and look at the javascript files within [here](https://github.com/lduarte1991/hx-annotations-lti/tree/residential/hx_lti_tools/hx_lti_initializer/static) cause that's where all the stuff is and [here](https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer/templates/tx/detail.html)'s the html template that calls the javascript.

**Comment by apanimesh061** [comment]
Hi,
That's ok. I will have a look at all this.

Yeah, I basically needed only the Annotations part.


Thanks for your help.

On Wed, May 20, 2015 at 12:53 PM, lduarte1991 <notifications@github.com>
wrote:

> Unfortunately, I don't have much time to help debug (sorry!), but here's
> some things that might help you:
>
> I would recommend you read up on the LTI Framework
> <http://www.imsglobal.org/LTI/v1p1/ltiIMGv1p1.html> and how it works. You
> can't just go to the URL of the tool, it's an LTI tool, so you need
> something like a launcher on edX or Canvas or your own personal server, and
> requires access via the initializer
> <https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer>.
> You need to point it to the consumer URL of the server you're running it
> from here
> <https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer/__init__.py>.
> And then validate it using the functions here
> <https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer/views.py>.
>
>
> Any other URLs can be found in the patterns within the urls.py files
> throughout the different apps.
>
> Make sure you have a handle on LTI and Django, otherwise the set up won't
> make sense. If all you need is the Annotator component of it, skip the set
> up above and look at the javascript files within here
> <https://github.com/lduarte1991/hx-annotations-lti/tree/residential/hx_lti_tools/hx_lti_initializer/static>
> cause that's where all the stuff is and here
> <https://github.com/lduarte1991/hx-annotations-lti/blob/residential/hx_lti_tools/hx_lti_initializer/templates/tx/detail.html>'s
> the html template that calls the javascript.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lduarte1991/hx-annotations-lti/issues/1#issuecomment-103957404>
> .
>



-- 
Thanks and regards,
Animesh Pandey
Graduate Student
Northeastern University
Boston, MA, USA
